### ISSUE TITLE
Mist Brightness is Blinding

### ISSUE THREAD

**Issue by Shwigz** [zesterer/openmw-volumetric-clouds#13]
Hi, I'm having an issue where the mist is just way too bright, and generally just doesn't look how it does in the screenshots at all.

![image](https://user-images.githubusercontent.com/120454240/207270743-a2521c84-f103-4189-8236-3c0dee5d1b65.png)
This is looking out towards Lake Amiya north of Vivec.

![vivec](https://user-images.githubusercontent.com/120454240/207271103-e9ed1ecf-6e55-464f-b315-8fad8b79c4b1.png)
Looking at Vivec from Pelagiad.

![seyda](https://user-images.githubusercontent.com/120454240/207271382-8406042d-d324-4b15-8cc9-c62d6e6bed1d.png)
And this is looking out from Seyda Neen.

As you can see, the mist is extremely bright and it also doesnt seem to be loading the textures or something. 

Also, when up high the mist creates this strange banding effect and just doesn't look at all how it's supposed to.
![bands](https://user-images.githubusercontent.com/120454240/207272966-3df12f9f-7f42-4b68-9863-3041f9dfd90f.png)

I'm on the latest dev build and I'll triple checked all my settings to be correct, so I'm truly at a loss about how to fix this.

**Comment by zesterer** [comment]
I did make some recent changes to the way mist is calculated that probably inadvertently introduced this. I'll play with it a bit tonight to see if I can come up with something a bit more reasonable.

**Comment by Shwigz** [comment]
Awesome, thank you so much!

**Comment by zesterer** [comment]
This is fixed? I don't think I made any changes...

**Comment by Shwigz** [comment]
That's strange, I downloaded the update you made on the 13th and the problem was gone, so I assumed you had fixed it.

**Comment by zesterer** [comment]
Oh, fair enough! Might have just been that you caught an older version with a bug!
