### ISSUE TITLE
Fog is present inside interiors

### ISSUE THREAD

**Issue by ines-gorgon** [zesterer/openmw-volumetric-clouds#14]
I had been using an older version (I think from August) for a while and I recently upgraded to the most recent version, dated today (12/13/22). I am using the most recent development version of OpenMW. With the current version of your shaders, fog now seems to be showing up inside interiors. 

With the shader OFF:
![OpenMW  12_13_22_20_12--p9nd](https://user-images.githubusercontent.com/90648056/207489212-74073d4e-24f4-458b-b2b3-6e0db6e8d3ac.jpg)
With the shader ON:
![OpenMW  12_13_22_20_12--N6na](https://user-images.githubusercontent.com/90648056/207489216-8b1f212d-4231-46e0-aaca-cb1e7a031790.jpg)

**Comment by zesterer** [comment]
This is a recent change I made as a result of feedback from other players: it was felt by several people that having a small amount of internal dust was a nice effect that improves the atmosphere of interiors.

That said, I can definitely add a toggle for it in the settings to allow it to be turned off, if desirable?

**Comment by ines-gorgon** [comment]
If you wouldn't mind: yes please to a toggle or slider controlling it.

**Comment by zesterer** [comment]
Check out the latest version of the mod, I've added an 'Interior Mist' slider in the 'Extra' section. Hopefully it's enough!

**Comment by ines-gorgon** [comment]
Nice! Thank you!
