### ISSUE TITLE
Starting the game with clouds enabled in an interior cell makes everything black

### ISSUE THREAD

**Issue by critkitten** [zesterer/openmw-volumetric-clouds#15]
I test OpenMW-0.48.0-RC4-win64.exe on windows and branch openmw-48 @ [5b56fe8d0db108b18dcfb03ee558af5bbc495f06](https://gitlab.com/OpenMW/openmw/-/commit/5b56fe8d0db108b18dcfb03ee558af5bbc495f06) on linux.

See also https://gitlab.com/modding-openmw/modding-openmw.com/-/issues/140

**Comment by zesterer** [comment]
Does this happen on development builds too? Regardless, this seems like a bug with OpenMW, not this shader: shaders are deliberately stateless and cannot cause this sort of behaviour to occur by themselves.

**Comment by critkitten** [comment]
Yes. 00b142eed7963940a8ec2b5b05ec5462c6f5c11b

**Comment by mdmallardi** [comment]
I can confirm this as well using the openmw 0.48.0 rc9 generic linux build from openmw.org.  First experienced it when starting a new game with my partner.  We were very confused. :-)

**Comment by zesterer** [comment]
I think this can be temporarily fixed by turning 'interior mist' down to 0 in the F2 settings menu.

**Comment by Bluedasher** [comment]
I had this same issue. Spent 2 hours trying to isolate which mod was causing the issue. I figured out it was this one. Your recommendation to turn "interior mist" down to 0 solved it. Thank you.

**Comment by zesterer** [comment]
This should now be properly fixed in the latest build.
