### ISSUE TITLE
Light sources like candles are glowing but there is no flame

### ISSUE THREAD

**Issue by Krachkratz** [zesterer/openmw-volumetric-clouds#20]
Could that be caused by this mod? Sometimes a flame is visible if i walk really close. 
The mist is beautiful, thanks for your work.

**Comment by zesterer** [comment]
Yes, this is the 'point glow' effect. You can turn it down or off in the mod settings in the F2 menu, if you wish.

**Comment by Krachkratz** [comment]
Thanks, my fault I didn't knew I could change it. I play in VR so it looks better with flames.
