### ISSUE TITLE
Glow for Multi-candle lights is incorrect

### ISSUE THREAD

**Issue by AbduSharif** [zesterer/openmw-volumetric-clouds#22]
Old version of light glow had enough radius for the glow to suit the multi-candle lights, new glow is suitable only for single candle lights, can this be fixed?

**Comment by AbduSharif** [comment]
If there's not an easy way to do this in the shader alone; Lua can check for the ID or name of lights, which could help here, I guess?

**Comment by AbduSharif** [comment]
Checking for name can also help to set unlit candles...etc to not have glow.

**Comment by AbduSharif** [comment]
As I said above it dies provide the information with Lua, but fi you can't use that then it's fine, as you said there's a way to workaround this in your shader already.

**Comment by AbduSharif** [comment]
Here's how it would look like after doing what Zesterer mentioned (their screenshot):
![image](https://github.com/zesterer/openmw-volumetric-clouds/assets/57298920/de0f50bb-07e3-402b-8503-6f7d4e39e1f0)

**Comment by zesterer** [comment]
I've just changed the default point glow parameters to be a bit closer to this, meaning they should behave better for chandeliers (although, as mentioned, this is entirely incidental: the mod still doesn't differentiate between them and regular light sources).
