### ISSUE TITLE
Random black clouds

### ISSUE THREAD

**Issue by TheMadJazz** [zesterer/openmw-volumetric-clouds#23]
I have no clue what the problem is. It just happens sometimes.

![screenshot005](https://user-images.githubusercontent.com/129596947/229287141-ef9de886-e0b0-4e61-b36c-f3b7f276830c.png)
![screenshot006](https://user-images.githubusercontent.com/129596947/229287145-d847bdd0-6aec-40f5-94c5-b0130e11c731.png)
![screenshot007](https://user-images.githubusercontent.com/129596947/229287148-bde35867-07af-4543-9ea7-7c5b7a7576e1.png)
![screenshot008](https://user-images.githubusercontent.com/129596947/229287153-dd31900f-6fe0-4e28-8b3e-c966617bd491.png)

**Comment by TheMadJazz** [comment]
Reinstalling the shader helped for some reason.

**Comment by zesterer** [comment]
How odd!
