### ISSUE TITLE
Weird point glow after fighting mages

### ISSUE THREAD

**Issue by poperigby** [zesterer/openmw-volumetric-clouds#26]
I know this sounds strange, but I've narrowed down an issue to this shader, only when "Point Glow" is turned on. After I've fought some mages (Therana seems to trigger it, so it must be a certain spell she uses), and point glow appears beneath my character's feet, and doesn't go away no matter what.

![Screenshot_20230827_200354](https://github.com/zesterer/openmw-volumetric-clouds/assets/20866468/a7fe2143-34d6-4fa7-8047-3e1049a30f86)

**Comment by poperigby** [comment]
It seems simply hitting Therana causes this glow to show up.

**Comment by poperigby** [comment]
I'm now noticing that my feet are still casting light even without the point glow, so I think this is just exposing a weird issue.

**Comment by zesterer** [comment]
Hmm, seems like some janky feature of original Morrowind that looked 'good enough' with its primitive lighting model but falls apart for anything more complex :(

**Comment by poperigby** [comment]
That was my original thought, but then I realized it's actually coming from Protective Guards, and it happens any time you acquire a bounty. I thought it was just from attacking mages, because those were the only people I had tried attacking, the Ahnassi bullies and Therana, who both happened to be mages.
