### ISSUE TITLE
With this shader enabled, mouse cursor is laggy in menus

### ISSUE THREAD

**Issue by poperigby** [zesterer/openmw-volumetric-clouds#28]
I'm not entirely sure if this is actually caused by this shader, but it only seems to happen with it enabled. When I'm in a menu (inventory, pause menu, etc.), my mouse cursor is very laggy. I checked, and it's only in OpenMW, not my entire OS. Disabling this completely fixes the issue. 

Please tell me if it's impossible for this mod to cause that issue.

**Comment by zesterer** [comment]
To me, this just sounds like regular old lag induced by higher GPU load. I imagine that your GPU is operating at or close to its maximum performance when the shader is enabled. Turning down some of the shader settings might improve this.

**Comment by poperigby** [comment]
That's possible, but I wouldn't think OpenMW with minimal graphics mods and no shadows would be pushing my RX 5700 XT to it's knees, but I totally could be wrong here. It also is only caused with the clouds shader. No other shaders cause it, and even enabling shadows doesn't cause it.

Also, it only causes lag in the menus, not when I move my camera around in-game.

Here's a screenshot of me looking at an area that causes it:
![Screenshot_20230829_110914](https://github.com/zesterer/openmw-volumetric-clouds/assets/20866468/ffddd7a0-b0c6-4a22-823e-c17d348b732d)

**Comment by zesterer** [comment]
Well, I'm not sure. This seems like a question for the OpenMW core project. This mod does nothing to anything UI-related, it's purely a post-processing shader. That said, if you have the shader settings turned up very high, it's going to make even the most powerful GPU scream and needing to render an extra UI layer for the cursor might just push it over the edge.

**Comment by poperigby** [comment]
You're probably right. Thanks for the help.
