### ISSUE TITLE
Effects inside of buildings/makes interiors lighter

### ISSUE THREAD

**Issue by BASEDNWAH** [zesterer/openmw-volumetric-clouds#8]
I noticed as soon as I turned it on in F2 processing menu the interior of the shop I was in at the time got instantly brighter/almost seemed like it had fog inside it a little? I am also using True Lights and Darkness mod.

Great mod by the way very cool! Tanks my fps a bit too much though even on higher settings. Using a GTX 760, will maybe go back to it when I have a better PC :)

**Comment by zesterer** [comment]
Do you have a screenshot of this happening? Interiors should have clouds disabled.

Make sure you play with the 'quality' setting, it significantly alters the performance cost of the mod.

**Comment by BASEDNWAH** [comment]
> 

I just went and got some I was lazy before! It's inside Caldera armour shop. The lighter one is with clouds turned on the darker one is without them on. 
![screenshot003](https://user-images.githubusercontent.com/109309480/180519940-03d091b0-ee5c-4056-9dd5-f08688bb28fb.png)
![screenshot002](https://user-images.githubusercontent.com/109309480/180519946-90869ad8-a580-44f0-9214-074a57bd3caf.png)

**Comment by BASEDNWAH** [comment]
Here is a nice video of it for you. 

https://www.youtube.com/watch?v=332bqgljmUM

**Comment by zesterer** [comment]
I think what you're seeing is the glow from the candles. At the bottom of the mod settings, there's a slider to increase/decrease this.

**Comment by BASEDNWAH** [comment]
> 

Yes!!! Point glow strength slider? This fixes it  ty! You can get some interesting effects with torches/lanterns/candles fiddling with this lider. Only annoying thing is the kind of pulse the lights all have but I think that is Todd Howard's fault.

**Comment by BASEDNWAH** [comment]
Great mod!
